/// ******************* COMPLETE FIXED DIALOGS.DART *******************
/// File Name: dialogs.dart
/// Description: Complete dialogs file with ALL fixes
/// Fixed Issues:
///   1. Edit mode detection logic
///   2. Document ID preservation during edit
///   3. Data loss during edit (departments, providers, etc.)
///   4. Mounted check error
///   5. Responsive dialog sizing
/// Last Update: February 2026

import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:demo_app/features/services_management_module/presentation/s1_home_page_services/ui/widgets/shared_prefs.dart';
import 'package:lottie/lottie.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:demo_app/generated/l10n.dart';
import 'package:demo_app/core/utils/shared.dart';
import 'package:demo_app/features/services_management_module/data/helper/services_prefs_employee.dart';
import 'package:demo_app/core/theme/app_colors.dart';
import 'package:demo_app/core/custom/5-custom_button.dart';
import 'package:demo_app/core/widgets/services_management/custom_botton.dart';
import 'package:demo_app/core/theme/app_font_size.dart';

import 'package:demo_app/core/theme/app_text_styles.dart';

import 'package:demo_app/features/services_management_module/data/models/model_employee.dart';
import 'package:demo_app/features/services_management_module/data/models/services_history_model.dart';
import 'package:demo_app/features/services_management_module/presentation/controller/services_manager_cubit.dart';
import 'package:demo_app/core/custom/37-custom_navigate.dart';

import 'package:demo_app/features/services_management_module/presentation/s1_home_page_services/ui/pages/home_page_services_toggle.dart';

Future<void> showCreateServiceDialog(
    BuildContext context,
    ServicesHistoryModel? modelCreate,
    Map<String, Map<int, bool>> mapModel,
    bool switchOne,
    bool switchTwo,
    ) async {
  final stableNavCtx = context;

  // ✅ IMPROVED: Better edit mode detection
  bool isCreatingNew = false;
  bool isDraft = false;
  bool isEditingExisting = false;

  if (modelCreate != null) {
    final docId = modelCreate.currentId;
    final state = modelCreate.currentState;

    // Check if it's a SharedPrefs draft (starts with 'draft_')
    if (docId.startsWith('draft_')) {
      isDraft = true;
    }
    // ✅ FIX: Correct edit detection - check for active/submitted state AND real ID
    else if (docId.isNotEmpty &&
        !docId.startsWith('draft_') &&
        !docId.startsWith('User') &&
        (state == 'active' || state == 'submitted' || state == 'inactive')) {
      isEditingExisting = true;
    }
    // OR if it has a real Firebase ID format (not generated by our app)
    else if (docId.isNotEmpty &&
        !docId.startsWith('draft_') &&
        modelCreate.currentDurationOfServices.isNotEmpty &&
        modelCreate.currentDurationOfServices != "-") {
      isEditingExisting = true;
    }
    // Otherwise it's creating new
    else {
      isCreatingNew = true;
    }
  } else {
    // No model at all = creating new
    isCreatingNew = true;
  }

  return showDialog(
    context: stableNavCtx,
    barrierDismissible: true,
    builder: (dlgCtx) {
      final lightMode = Theme.of(context).brightness == Brightness.light;

      // Get screen dimensions
      final screenWidth = MediaQuery.of(dlgCtx).size.width;
      final screenHeight = MediaQuery.of(dlgCtx).size.height;
      final orientation = MediaQuery.of(dlgCtx).orientation;

      // Determine platform type
      final isMobile = screenWidth < 600;
      final isTablet = screenWidth >= 600 && screenWidth < 1200;
      final isDesktop = screenWidth >= 1200;
      final isPortrait = orientation == Orientation.portrait;

      // Calculate responsive dimensions
      double dialogWidth;
      double dialogHeight;
      double lottieSize;
      double titleFontSize;
      double messageFontSize;
      double buttonWidth;
      double buttonHeight;

      if (isMobile) {
        dialogWidth = screenWidth * 0.85;
        dialogHeight = isPortrait
            ? screenHeight * 0.35
            : screenHeight * 0.55;
        lottieSize = 60.0;
        titleFontSize = 18.0;
        messageFontSize = 14.0;
        buttonWidth = (dialogWidth - 80) * 0.4;
        buttonHeight = 36.0;
      } else if (isTablet) {
        if (isPortrait) {
          dialogWidth = screenWidth * 0.7;
          dialogHeight = screenHeight * 0.3;
        } else {
          dialogWidth = screenWidth * 0.5;
          dialogHeight = screenHeight * 0.45;
        }
        lottieSize = 70.0;
        titleFontSize = 20.0;
        messageFontSize = 15.0;
        buttonWidth = 135.0;
        buttonHeight = 38.0;
      } else {
        dialogWidth = 450.0;
        dialogHeight = 280.0;
        lottieSize = 80.0;
        titleFontSize = 22.0;
        messageFontSize = 16.0;
        buttonWidth = 140.0;
        buttonHeight = 40.0;
      }

      dialogWidth = dialogWidth.clamp(300.0, 600.0);
      dialogHeight = dialogHeight.clamp(200.0, 400.0);

      return Dialog(
        backgroundColor: Theme.of(dlgCtx).brightness == Brightness.light
            ? AppColors.white
            : AppColors.chatBackground,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8.0),
        ),
        child: Container(
          width: 500.w,
      //    height: dialogHeight,
          padding: EdgeInsets.all(isMobile ? 12.0 : 15.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              // Lottie Animation
              Flexible(
                flex: 2,
                child: Lottie.asset(
                  isEditingExisting
                      ? "assets/lottie/createServices.json"
                      : isDraft
                      ? "assets/lottie/draft.json"
                      : "assets/lottie/createServices.json",
                  width: lottieSize,
                  height: lottieSize,
                  fit: BoxFit.contain,
                  repeat: true,
                  animate: true,
                ),
              ),

              SizedBox(height: isMobile ? 10.0 : 15.0),

              // Title
              Flexible(
                flex: 1,
                child: Text(
                  isEditingExisting
                      ? S.of(dlgCtx).editingService
                      : isDraft
                      ? S.of(dlgCtx).draftService
                      : S.of(dlgCtx).creatingService,
                  style: AppTextStyles.font20BlackCairoMedium.copyWith(
                    color: lightMode ? AppColors.blackButton : AppColors.white,
                  ),
                  textAlign: TextAlign.center,
                ),
              ),

              SizedBox(height: isMobile ? 8.0 : 12.0),

              // Message
              Flexible(
                flex: 2,
                child: Text(
                  isEditingExisting
                      ? S.of(dlgCtx).areYouSureEditService
                      : isDraft
                      ? S.of(dlgCtx).areYouSureYouWantToSaveAsDraft
                      : S.of(dlgCtx).areYouSureCreateService,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: messageFontSize,
                    fontWeight: FontWeight.w500,
                    color: Theme.of(dlgCtx).brightness == Brightness.light
                        ? AppColors.secondaryText
                        : AppColors.grey,
                  ),
                ),
              ),

              SizedBox(height: isMobile ? 12.0 : 15.0),

              // Buttons
              Flexible(
                flex: 1,
                child: Padding(
                  padding: EdgeInsets.symmetric(
                      horizontal: isMobile ? 20.0 : 56.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      // No Button
                      Flexible(
                        child: customButtonAnimation(
                          title: S.of(dlgCtx).no,
                          function: () {
                            Navigator.of(stableNavCtx, rootNavigator: true).pop();
                          },
                          textStyle: TextStyle(
                            fontSize: messageFontSize,
                            color: AppColors.black,
                            fontWeight: FontWeight.w500,
                          ),
                          width: buttonWidth,
                          height: buttonHeight,
                          radius: 4.0,
                          color: AppColors.secondaryButton,
                        ),
                      ),

                      SizedBox(width: isMobile ? 10.0 : 20.0),

                      // Yes/Update Button
                      Flexible(
                        child: customButtonAnimation(
                          title: S.of(dlgCtx).yes,
                          function: () async {
                            try {

                              final prefs = await SharedPreferences.getInstance();

                              // ✅ CRITICAL FIX: Load all data with fallback to modelCreate
                              // This prevents data loss during edit when user doesn't visit all screens

                              final servicesProviderNameEnglish =
                                  await SharedPrefsHelper.getString("service_name_en")
                                      ?? modelCreate?.currentServiceNameEnglish
                                      ?? '';

                              final servicesProviderNameArabic =
                                  await SharedPrefsHelper.getString("service_name_ar")
                                      ?? modelCreate?.currentServiceNameArabic
                                      ?? '';

                              final servicesDescriptionEnglish =
                                  await SharedPrefsHelper.getString("service_description_en")
                                      ?? modelCreate?.currentServiceDescriptionEnglish
                                      ?? '';

                              final servicesDescriptionArabic =
                                  await SharedPrefsHelper.getString("service_description_ar")
                                      ?? modelCreate?.currentServiceDescriptionArabic
                                      ?? '';

                              final selectedDuration =
                                  await SharedPrefsHelper.getString("duration_value")
                                      ?? modelCreate?.currentDurationOfServices
                                      ?? '';

                              final selectedDurationUnit =
                                  await SharedPrefsHelper.getString("duration_unit")
                                      ?? modelCreate?.currentSelectedDurationUnit
                                      ?? '';

                              // ✅ CRITICAL: Lists with fallback to preserve existing data
                              final selectedProvidedEmployees =
                                  await SharedPrefsEmployeeHelper.getSelectedEmployees()
                                      ?? modelCreate?.currentProviderServices
                                      ?? [];

                              final selectedDepartment =
                                  await SharedPrefsDepartmentsHelper.getDepartments()
                                      ?? modelCreate?.currentSelectDepartment
                                      ?? [];

                              final selectedApprovedEmployees =
                                  await SharedPrefsApprovalHelper.getApprovalCycle()
                                      ?? modelCreate?.currentApprovalCycle
                                      ?? [];

                              final slaOne = await SharedPrefsHelper.getString('sla_one')
                                  ?? modelCreate?.currentSlaOneControllerEnglish
                                  ?? '';

                              final slaTwo = await SharedPrefsHelper.getString('sla_two')
                                  ?? modelCreate?.currentSlaTwoControllerEnglish
                                  ?? '';

                              final notifyRequesterChecked =
                                  await SharedPrefsHelper.getBool('Notify Service Requester_checked')
                                      ?? modelCreate?.currentNotifyRequesterChecked
                                      ?? false;

                              final notifyProviderChecked =
                                  await SharedPrefsHelper.getBool('Notify Service Provider_checked')
                                      ?? modelCreate?.currentNotifyProviderChecked
                                      ?? false;

                              final notifyManagerChecked =
                                  await SharedPrefsHelper.getBool('Notify Provider Manager_checked')
                                      ?? modelCreate?.currentNotifyManagerChecked
                                      ?? false;

                              final notifyProviderSwitches =
                                  mapModel[S.of(dlgCtx).notifyServiceProvider] ?? {};
                              switchOne = notifyProviderSwitches[0] ?? false;

                              final notifyManagerSwitches =
                                  mapModel[S.of(dlgCtx).notifyProviderManager] ?? {};
                              switchTwo = notifyManagerSwitches[0] ?? false;

                              // ✅ DEBUG: Print loaded data

                              // ✅ FIX: Proper ID generation logic
                              String docId;
                              if (isEditingExisting && modelCreate?.currentId.isNotEmpty == true) {
                                // Use existing document ID for edit
                                docId = modelCreate!.currentId;
                              } else if (isDraft && modelCreate?.currentId.isNotEmpty == true) {
                                // For drafts, check if it's a temp ID or real ID
                                if (modelCreate!.currentId.startsWith('draft_') ||
                                    modelCreate.currentId.startsWith('User')) {
                                  // It's a temp ID, generate new one
                                  final now = Timestamp.now();
                                  final formattedDate = DateFormat("MMMdd_yyyy").format(now.toDate());
                                  final randomId = Random().nextInt(100000);
                                  docId = "User$randomId$formattedDate";
                                } else {
                                  // It's a real ID, use it
                                  docId = modelCreate.currentId;
                                }
                              } else {
                                // Creating completely new service
                                final now = Timestamp.now();
                                final formattedDate = DateFormat("MMMdd_yyyy").format(now.toDate());
                                final randomId = Random().nextInt(100000);
                                docId = "User$randomId$formattedDate";
                              }

                              final bool notifyRequesterSwitch0FromMap =
                                  mapModel[S.of(dlgCtx).notifyServiceProvider]?[0] ?? false;
                              final bool notifyManagerSwitch1FromMap =
                                  mapModel[S.of(dlgCtx).notifyProviderManager]?[0] ?? false;

                              final limitAvailabilityFlag =
                                  await SharedPrefsHelper.getBool('limitAvailability') ??
                                      (modelCreate?.currentLimitAvailability ?? false);
                              final requireApprovalFlag =
                                  await SharedPrefsHelper.getBool('requireApproval') ??
                                      (modelCreate?.currentRequireApproval ?? false);

                              final selectedDepartmentFinal =
                              limitAvailabilityFlag ? (selectedDepartment.isNotEmpty ? selectedDepartment : []) : [];
                              final List<EmployeeEntityModell> selectedApprovedEmployeesFinal =
                              requireApprovalFlag ? (selectedApprovedEmployees.isNotEmpty ? selectedApprovedEmployees : []) : [];

                              // Create ServicesHistoryModel
                              final model = ServicesHistoryModel.createNew(
                                id: docId,
                                state: isEditingExisting ? (modelCreate!.currentState) : 'active',
                                status: (await SharedPrefsHelper.getBool('service_status')) == true ? "active" : "inactive",
                                serviceNameEnglish: servicesProviderNameEnglish,
                                serviceNameArabic: servicesProviderNameArabic,
                                serviceDescriptionEnglish: servicesDescriptionEnglish,
                                serviceDescriptionArabic: servicesDescriptionArabic,
                                durationOfServices: selectedDuration,
                                selectedDurationUnit: selectedDurationUnit,
                                providerServices: selectedProvidedEmployees,
                                selectDepartment: selectedDepartmentFinal,
                                approvalCycle: selectedApprovedEmployeesFinal,
                                limitAvailability: limitAvailabilityFlag,
                                requireApproval: requireApprovalFlag,
                                slaOneControllerEnglish: slaOne,
                                slaTwoControllerEnglish: slaTwo,
                                notifyRequesterChecked: notifyRequesterChecked,
                                notifyProviderChecked: notifyProviderChecked,
                                notifyManagerChecked: notifyManagerChecked,
                                notifyRequesterSwitch0: notifyRequesterSwitch0FromMap,
                                notifyManagerSwitch1: notifyManagerSwitch1FromMap,
                                emailRequester: prefs.getString("emailRequester") ?? '',
                              );

                              // ✅ FIX: Use correct service method based on mode
                              final serviceCall = isEditingExisting
                                  ? ServicesManagerCubit.get(stableNavCtx).updateService(docId, model)
                                  : ServicesManagerCubit.get(stableNavCtx).saveService(docId, model);

                              ServicesManagerCubit.get(stableNavCtx).saveRequestService(docId, model);

                              await serviceCall.then((_) async {

                                await SharedPrefsHelper.setBool('service_status', true);
                                await SharedPrefsHelper.setString('service_image_url', '');

                                // Clear draft if from SharedPrefs
                                if (modelCreate?.currentId?.startsWith('draft_') == true) {
                                  try {
                                    await SharedPrefsServiceMaster.removeDraftById(modelCreate!.currentId!);
                                  } catch (e) {
                                  }
                                }

                                // Clear temp data for new services
                                if (!isEditingExisting) {
                                  await SharedPrefsHelper.setString('sla_one', '');
                                  await SharedPrefsHelper.setString('sla_two', '');
                                  await SharedPrefsHelper.setString('service_name_en', '');
                                  await SharedPrefsHelper.setString('service_name_ar', '');
                                  await SharedPrefsHelper.setString('service_description_en', '');
                                  await SharedPrefsHelper.setString('service_description_ar', '');
                                  await SharedPrefsHelper.setString('duration_value', '');
                                  await SharedPrefsHelper.setString('duration_unit', '');
                                }

                                final cubit = ServicesManagerCubit.get(stableNavCtx);
                                cubit.docService = null;

                                ServicesManagerCubit.get(stableNavCtx).getAllServices();

                                Navigator.of(stableNavCtx, rootNavigator: true).pop();
                                correctShowDialog(stableNavCtx, model, isEditingExisting);
                              });
                            } catch (e, st) {
                              Navigator.of(stableNavCtx, rootNavigator: true).pop();

                              showDialog(
                                context: stableNavCtx,
                                builder: (context) => AlertDialog(
                                  title: Text(S.of(context).error),
                                  content: Text('Failed to ${isEditingExisting ? "update" : "create"} service: $e'),
                                  actions: [
                                    customButton(
                                      title: 'OK',
                                      function: () => Navigator.pop(context),
                                      width: 80.sp,
                                      height: 36.sp,
                                      color: AppColors.primary,
                                      textColor: AppColors.textButton,
                                    ),
                                  ],
                                ),
                              );
                            }
                          },
                          textStyle: TextStyle(
                              fontSize: messageFontSize,
                              fontWeight: FontWeight.w500,
                              color: AppColors.textButton),
                          width: buttonWidth,
                          height: buttonHeight,
                          radius: 4.0,
                          color: AppColors.primary,
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              SizedBox(height: isMobile ? 4.0 : 4.0),
            ],
          ),
        ),
      );
    },
  );
}

Future<void> correctShowDialog(
    BuildContext context,
    ServicesHistoryModel model,
    [bool isEditing = false]
    ) async

{
  final stableNavCtx = context;
  bool navigated = false;

  // ✅ Only clear selection when creating new service, not editing
  if (!isEditing) {
    await _clearSelectionAfterServiceCreation(stableNavCtx);
  }

  await showDialog(
    context: stableNavCtx,
    barrierDismissible: true,
    builder: (dialogCtx) {

      final isArabic = Localizations.localeOf(context).languageCode == 'ar';
      // Auto-close and navigate after 2 seconds
      Future.delayed(const Duration(seconds: 2), () {
        if (!navigated) {
          navigated = true;
          Navigator.of(stableNavCtx, rootNavigator: true).pop();
          navigateAndFinish(stableNavCtx, LayoutScreenServices());
        }
      });

      return WillPopScope(
        onWillPop: () async {
          if (!navigated) {
            navigated = true;
            Navigator.of(stableNavCtx, rootNavigator: true).pop();
            navigateAndFinish(stableNavCtx, LayoutScreenServices());
          }
          return false;
        },
        child: GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () {
            if (!navigated) {
              navigated = true;
              Navigator.of(stableNavCtx, rootNavigator: true).pop();
              navigateAndFinish(stableNavCtx, LayoutScreenServices());
            }
          },
          child: Dialog(
            backgroundColor: Theme.of(dialogCtx).brightness == Brightness.light
                ? AppColors.white
                : AppColors.chatBackground,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8.r),
            ),
            child: Container(
              width: 500.w, // ✅ Fixed width using ScreenUtil
              padding: EdgeInsets.all(24.r), // ✅ Responsive padding
              child: Column(
                mainAxisSize: MainAxisSize.min, // ✅ This makes height dynamic
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  // Success Animation
                  Lottie.asset(
                    'assets/lottie/approved.json',
                    width: 70.sp,
                    height: 70.sp,
                    fit: BoxFit.contain,
                    repeat: true,
                  ),

                  // space
                  SizedBox(height: 25.h),

                  // Title - Different for Edit vs Create
                  Text(
                    isEditing
                        ? S.of(context).servicesUpdated
                        : S.of(dialogCtx).createService,
                    textAlign: TextAlign.center,
                    style: AppTextStyles.font20BlackCairoMedium.copyWith(
                      color: Theme.of(dialogCtx).brightness == Brightness.light
                          ? AppColors.blackButton
                          : AppColors.white,
                    ),
                  ),

                  // space
                  SizedBox(height: 18.h),

                  // Message - Different for Edit vs Create
                  Text(
                    isEditing
                        ? isArabic ? "تم تحديث الخدمة بنجاح" : "Service Updated Successfully"

                        : isArabic ?  "تم إنشاء الخدمة بنجاح" :  "Service Created Successfully",

                    textAlign: TextAlign.center,
                    style: AppTextStyles.font15BlackCairoRegular.copyWith(
                      color: Theme.of(dialogCtx).brightness == Brightness.light
                          ? AppColors.secondaryText
                          : AppColors.grey,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      );
    },
  );
}

Future<void> _clearSelectionAfterServiceCreation(BuildContext context) async {
  try {
    await SharedPrefsEmployeeHelper.clearSelectedEmployees();
    await SharedPrefsHelper.setString('current_draft_id', '');
    await SharedPrefsHelper.setString('current_service_docId', '');

    final cubit = ServicesManagerCubit.get(context);
    cubit.docService = null;

  } catch (e, st) {
  }
}

Future<void> showSavingDraftDialog(BuildContext context, VoidCallback onYesPressed) async {
  await showDialog(
    context: context,
    barrierDismissible: false,
    builder: (context) => Dialog(
      backgroundColor: Theme.of(context).brightness == Brightness.light
          ? AppColors.white
          : AppColors.chatBackground,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8.r)),
      child: Padding(
        padding: EdgeInsets.all(15.r),
        child: SizedBox(
          width: 411.sp,
          height: 210.sp,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Lottie.asset(
                'assets/lottie/createServices.json',
                width: 70.w,
                height: 70.h,
                fit: BoxFit.scaleDown,
              ),
              SizedBox(height: 20.h),
              Text(
                S.of(context).savingDraft,
                style: AppTextStyles.font20BlackCairoMedium.copyWith(
                  color: Theme.of(context).brightness == Brightness.light
                      ? AppColors.blackButton
                      : AppColors.white,
                ),
              ),
              SizedBox(height: 18.h),
              Text(
                S.of(context).pleaseWaitSaving,
                textAlign: TextAlign.center,
                style: AppTextStyles.font14BlackCairoMedium.copyWith(
                  color: Theme.of(context).brightness == Brightness.light
                      ? AppColors.secondaryText
                      : AppColors.grey,
                ),
              ),
              SizedBox(height: 20.h),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  customButtonAnimation(
                    title: S.of(context).no,
                    function: () {
                      Navigator.of(context).pop();
                    },
                    textStyle: AppTextStyles.font15BlackCairoRegular.copyWith(
                      color: AppColors.black,
                    ),
                    width: 135.sp,
                    height: 38.sp,
                    radius: 4.r,
                    color: AppColors.secondaryButton,
                  ),
                  customButtonAnimation(
                    title: S.of(context).yes,
                    function: () {
                      Navigator.of(context).pop();
                      onYesPressed();
                    },
                    textStyle: AppTextStyles.font15BlackCairoRegular.copyWith(
                        color: AppColors.textButton
                    ),
                    width: 135.sp,
                    height: 38.sp,
                    radius: 4.r,
                    color: AppColors.primary,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    ),
  );
}

Future<void> showDraftSavedSuccessDialog(BuildContext context) async {
  final rootContext = context;
  bool navigated = false;

  await showDialog(
    context: rootContext,
    barrierDismissible: true,
    builder: (dialogContext) {
      Future.delayed(Duration(seconds: 2), () {
        if (!navigated) {
          navigated = true;
          Navigator.of(dialogContext).pop();
          navigateAndFinish(rootContext, LayoutScreenServices());
        }
      });

      return WillPopScope(
        onWillPop: () async {
          if (!navigated) {
            navigated = true;
            Navigator.of(dialogContext).pop();
            navigateAndFinish(rootContext, LayoutScreenServices());
          }
          return false;
        },
        child: Dialog(
          backgroundColor: Theme.of(dialogContext).brightness == Brightness.light
              ? AppColors.white
              : AppColors.chatBackground,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () {
              if (!navigated) {
                navigated = true;
                Navigator.of(dialogContext).pop();
                navigateAndFinish(rootContext, LayoutScreenServices());
              }
            },
            child: Padding(
              padding: EdgeInsets.all(15.r),
              child: SizedBox(
                width: 411.sp,
                height: 170.sp,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Lottie.asset(
                      'assets/lottie/approved.json',
                      width: 70.sp,
                      height: 70.sp,
                    ),
                    SizedBox(height: 25.sp),
                    Text(
                      S.of(context).draftService,
                      textAlign: TextAlign.center,
                      style: AppTextStyles.font20BlackCairoMedium.copyWith(
                        color: Theme.of(context).brightness == Brightness.light
                            ? AppColors.blackButton
                            : AppColors.white,
                      ),
                    ),
                    SizedBox(height: 18.sp),
                    Text(
                      S.of(context).successfullyDraftedService,
                      textAlign: TextAlign.center,
                      style: AppTextStyles.font15BlackCairoRegular.copyWith(
                        color: Theme.of(context).brightness == Brightness.light
                            ? AppColors.blackButton
                            : AppColors.white,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      );
    },
  );
}
