import 'package:get/get.dart';

List<String> nationality = [
  "Afghan".tr,
  "Albanian".tr,
  "Algerian".tr,
  "American".tr,
  "Andorran".tr,
  "Angolan".tr,
  "Antiguans".tr,
  "Argentinean".tr,
  "Armenian".tr,
  "Australian".tr,
  "Austrian".tr,
  "Azerbaijani".tr,
  "Bahamian".tr,
  "Bahraini".tr,
  "Bangladeshi".tr,
  "Barbadian".tr,
  "Barbudans".tr,
  "Batswana".tr,
  "Belarusian".tr,
  "Belgian".tr,
  "Belizean".tr,
  "Beninese".tr,
  "Bhutanese".tr,
  "Bolivian".tr,
  "Bosnian".tr,
  "Brazilian".tr,
  "British".tr,
  "Bruneian".tr,
  "Bulgarian".tr,
  "Burkinabe".tr,
  "Burmese".tr,
  "Burundian".tr,
  "Cambodian".tr,
  "Cameroonian".tr,
  "Canadian".tr,
  "Cape Verdean".tr,
  "Central African".tr,
  "Chadian".tr,
  "Chilean".tr,
  "Chinese".tr,
  "Colombian".tr,
  "Comoran".tr,
  "Congolese".tr,
  "Costa Rican".tr,
  "Croatian".tr,
  "Cuban".tr,
  "Cypriot".tr,
  "Czech".tr,
  "Danish".tr,
  "Djibouti".tr,
  "Dominican".tr,
  "Dutch".tr,
  "East Timorese".tr,
  "Ecuadorean".tr,
  "Egyptian".tr,
  "Emirian".tr,
  "Equatorial Guinean".tr,
  "Eritrean".tr,
  "Estonian".tr,
  "Ethiopian".tr,
  "Fijian".tr,
  "Filipino".tr,
  "Finnish".tr,
  "French".tr,
  "Gabonese".tr,
  "Gambian".tr,
  "Georgian".tr,
  "German".tr,
  "Ghanaian".tr,
  "Greek".tr,
  "Grenadian".tr,
  "Guatemalan".tr,
  "Guinea-Bissauan".tr,
  "Guinean".tr,
  "Guyanese".tr,
  "Haitian".tr,
  "Herzegovinian".tr,
  "Honduran".tr,
  "Hungarian".tr,
  "I-Kiribati".tr,
  "Icelander".tr,
  "Indian".tr,
  "Indonesian".tr,
  "Iranian".tr,
  "Iraqi".tr,
  "Irish".tr,
  "Israeli".tr,
  "Italian".tr,
  "Ivorian".tr,
  "Jamaican".tr,
  "Japanese".tr,
  "Jordanian".tr,
  "Kazakhstani".tr,
  "Kenyan".tr,
  "Kittian and Nevisian".tr,
  "Kuwaiti".tr,
  "Kyrgyz".tr,
  "Laotian".tr,
  "Latvian".tr,
  "Lebanese".tr,
  "Liberian".tr,
  "Libyan".tr,
  "Liechtensteiner".tr,
  "Lithuanian".tr,
  "Luxembourger".tr,
  "Macedonian".tr,
  "Malagasy".tr,
  "Malawian".tr,
  "Malaysian".tr,
  "Maldivan".tr,
  "Malian".tr,
  "Maltese".tr,
  "Marshallese".tr,
  "Mauritanian".tr,
  "Mauritian".tr,
  "Mexican".tr,
  "Micronesian".tr,
  "Moldovan".tr,
  "Monacan".tr,
  "Mongolian".tr,
  "Moroccan".tr,
  "Mosotho".tr,
  "Motswana".tr,
  "Mozambican".tr,
  "Namibian".tr,
  "Nauruan".tr,
  "Nepalese".tr,
  "New Zealander".tr,
  "Nicaraguan".tr,
  "Nigerian".tr,
  "Nigerien".tr,
  "North Korean".tr,
  "Northern Irish".tr,
  "Norwegian".tr,
  "Omani".tr,
  "Pakistani".tr,
  "Palauan".tr,
  "Panamanian".tr,
  "Papua New Guinean".tr,
  "Paraguayan".tr,
  "Peruvian".tr,
  "Polish".tr,
  "Portuguese".tr,
  "Qatari".tr,
  "Romanian".tr,
  "Russian".tr,
  "Rwandan".tr,
  "Saint Lucian".tr,
  "Salvadoran".tr,
  "Samoan".tr,
  "San Marinese".tr,
  "Sao Tomean".tr,
  "Saudi".tr,
  "Scottish".tr,
  "Senegalese".tr,
  "Serbian".tr,
  "Seychellois".tr,
  "Sierra Leonean".tr,
  "Singaporean".tr,
  "Slovakian".tr,
  "Slovenian".tr,
  "Solomon Islander".tr,
  "Somali".tr,
  "South African".tr,
  "South Korean".tr,
  "South Sudanese".tr,
  "Spanish".tr,
  "Sri Lankan".tr,
  "Sudanese".tr,
  "Surinamer".tr,
  "Swazi".tr,
  "Swedish".tr,
  "Swiss".tr,
  "Syrian".tr,
  "Taiwanese".tr,
  "Tajik".tr,
  "Tanzanian".tr,
  "Thai".tr,
  "Togolese".tr,
  "Tongan".tr,
  "Trinidadian or Tobagonian".tr,
  "Tunisian".tr,
  "Turkish".tr,
  "Tuvaluan".tr,
  "Ugandan".tr,
  "Ukrainian".tr,
  "Uruguayan".tr,
  "Uzbekistani".tr,
  "Venezuelan".tr,
  "Vietnamese".tr,
  "Welsh".tr,
  "Yemenite".tr,
  "Zambian".tr,
  "Zimbabwean".tr,
];
